# This is an example Conda environment, for local development
name: ml-verbs
channels:
  - conda-forge
dependencies:
  - python=3.9 # minimum targeted version is currently 3.9
  - pip
  - pip:
      - -e ".[dev,dev_extras,docs]"
